### ISSUE TITLE
Vehicle Mileage Tracker

### ISSUE THREAD

**Issue by itachi1706** [itachi1706/CheesecakeUtilities#110]
Track Mileage and Vehicle use

- [x] Able to add vehicle types and define classes (2,3,4,5)
- [x] Using odometer to calculate distance
- [x] Have Date of travel, To and Purpose
- [x] Able to add records
- [x] Able to delete records created
- [x] Synchronize through Firebase Realtime Database
- [x] Hide Training Mileage with a menu item saved that can be persisted

_Sent from my Google Nexus 6P using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by itachi1706** [comment]
Can use Room library for SQLite handling

https://developer.android.com/topic/libraries/architecture/room.html

_Sent from my Huawei Nexus 6P using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by itachi1706** [comment]
Can use Firebase Realtime DB to sync for now. When the time comes where it gets too much for the free limits then we can consider going to self host or another sync service

**Comment by itachi1706** [comment]
Some Links

http://www.androidhive.info/2016/10/android-working-with-firebase-realtime-database/
https://firebase.google.com/docs/auth/android/manage-users
https://firebase.google.com/docs/database/

**Comment by itachi1706** [comment]
Seems like if I use Firebase Realtime DB I dont need to use Room, Firebase handles it automatically by setting offline persistance on

**Comment by itachi1706** [comment]
https://firebase.googleblog.com/2014/04/best-practices-arrays-in-firebase.html Read the part of "Use Push to create Unique IDs" as that will be useful for the records itself

**Comment by itachi1706** [comment]
Need to remember to update the Travis encrypted file as I updated something there

_Sent from my Google Nexus 6P using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by itachi1706** [comment]
This shall be continued at #120
