### ISSUE TITLE
Enhancement to Vehicle Mileage Tracker

### ISSUE THREAD

**Issue by itachi1706** [itachi1706/CheesecakeUtilities#120]
After releasing #110, these are the stuff to implement as an enhancement to the utility as its not as important

- [x] Able to view vehicles
- [x] Able to edit vehicles
- [x] Able to delete vehicles
- [x]  Add date time into the main view with all records
- [x] Able to update records created
- [x] Add Autocomplete for location and purpose and vehicle number
- [x] Calculate total mileage per class/vehicle type/all (stats view)
- [x] Stats for per day
- [x] Scrollbar to quick scroll through list
- [x] Quick jump to date

**Comment by itachi1706** [comment]
Moved remainder todos into #213. Issuing PR
