### ISSUE TITLE
Enhancement to barcode generation

### ISSUE THREAD

**Issue by itachi1706** [itachi1706/CheesecakeUtilities#161]
- [ ] Save History of barcodes generated
- [ ] View history
- [ ] Click to generate barcode in history with option to share
- [ ] Save button to save barcode to device
- [ ] Add ability to launch scanned barcode for action (if available) such as URL, phone numbers etc
- [ ] Make layout in multi window mode not look weird for scanning barcodes

_Sent from my Nexus 6P using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
